apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: cc
      image: kube_image:1.0
      ports:
         - containerPort: 8080

