apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 20
  selector:
    app: hello-world
  template:
    metadata:
       labels:
         app: hello-world
    spec:
      containers:
      - name: cc
        image: kube_image:1.0
        ports:
        - containerPort: 8080
